name: Hello world demo

on:
  push:
     branches:  
             main
             jobs:
                say Hello:
                   runs-on: ubantu-latest
                     steps:
                        name: checkout code
                          uses: actions/check out@v3

                          name: print Hello
                          run echo "hello github actions"
